site_name: My python docs
site_description: "Пример кастомной темы для MkDocs"
site_author: "Efim"
nav:
  - Home: index.md
  - uv: uv.md
  - MkDocs: mkdocs.md
theme:
  name: null
  custom_dir: theme/

